mysql: Parallel Dump Table Prototype
Summary:
This is the initial set of changes for a new DUMP TABLE statement that
supports parallel dumping of a table with a configurable number of
threads.

This greatly improves dump performance over single threaded dumping that
happens in OSC today, and doing it in the server allows greater control
over all aspects of performance and memory.

New command syntax:

  DUMP TABLE <table> INTO <file_or_path> [ WITH ( option [, option]) ]

where

  option :=

    THREADS = n
    | CHUNK_SIZE = n ROWS

Things to do in future diffs:
1. Support shared snapshots. Currently all workers start their own
   transactions and use their own snapshots. We want a consistent dump
   and will thus need to use the same snapshot. I will leverage the work
   done in T25358895, D6818855, D7017721, D22144183 to that end.
2. Support size-based chunking. Currently we only do row count based,
   which results in uneven distribution of chunk file sizes.
3. Support arbitrary select lists. Today, we only support selecting all
   columns from the table, whereas we may only want a subset for things
   like OSC when the new table drops some columns from the original.
   This is not strictly required because OSC can be changed to filter
   the redundant columns at load time via LOAD DATA FROM INFILE syntax,
   but would be nice nonetheless.
4. Support warm storage. Right now we only support local disk as a
   destination.
5. Consider supporting compression, though it isn't being used today in OSC.

Differential Revision: D53600791

fbshipit-source-id: 1f756be6df260f3b43675132d23a04d73a9b163c

-------------------------------------------------------------------------------------------

Fix macOS compilation errors in (#1432)

Summary:
```
sql/sql_dump.cc:610:48: error: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Werror,-Wformat]
                        table_ref->table_name, rownum));
                                               ^~~~~~
```

```
sql/sql_dump.cc:614:14: error: format specifies type 'long' but the argument has type 'int64_t' (aka 'long long') [-Werror,-Wformat]
             rownum, chunk_id);
             ^~~~~~
```

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1432

Differential Revision: D54334513

fbshipit-source-id: 07a325aa362bfa84b758c44b62bf04175a86bc91